const NEXT_PUBLIC_BACKENDLESS_API_BASE_URL =
	process.env.NEXT_PUBLIC_BACKENDLESS_API_BASE_URL;
const NEXT_PUBLIC_BACKENDLESS_API_KEY =
	process.env.NEXT_PUBLIC_BACKENDLESS_API_KEY;
const NEXT_PUBLIC_BACKENDLESS_APP_ID =
	process.env.NEXT_PUBLIC_BACKENDLESS_APP_ID;

export {
	NEXT_PUBLIC_BACKENDLESS_API_BASE_URL,
	NEXT_PUBLIC_BACKENDLESS_API_KEY,
	NEXT_PUBLIC_BACKENDLESS_APP_ID,
};
